language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "primefaces-extensions"
    token:
      secure: "M6/l2mCVSfggXqKQMmbgJKywJCccr+kpqFrjJXoMrmsMYmkGNCrGX5p6JNAn2Hzd8tLi7ldi4GJ9/rdX30KXYMQ/5WzK7gGX8PkMJT1WEAJA4mNrXGBJk4/ZlFpS2Nb6fUud7eZf37E6XQvXd9qyUBtzWUBycYLmbUUA+0xudUc="
jdk:
  - oraclejdk8
install:
  - git clone https://github.com/primefaces-extensions/master-pom && cd master-pom && mvn install && cd ..
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
