language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "primefaces-extensions"
    token:
      secure: "06c1ac7a24538536eacbdf4198bca0df1e8204e7"
jdk:
  - oraclejdk8
install:
  - git clone https://github.com/primefaces-extensions/master-pom && cd master-pom && mvn install && cd ..
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization={ORG_KEY} -Dsonar.login={GENERATED_KEY_ON_SONARCLOUD_SECURITY} -Dsonar.branch={BRANCH_NAME}
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
