language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "pr1m3fac3sext3ns1ons"
jdk:
  - oraclejdk8
install:
  - git clone https://github.com/primefaces-extensions/master-pom && cd master-pom && mvn install && cd ..
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
